# Some segments of this script contain AI generated/refactored code, and there are comments that tell whether it has been generated/refactored with AI.
# I only used AI to optimize my existing code and to generate helper functions that would be faster to make by AI than by me.

# I'm not adding comments to this because it's been like 2 months since I last seen this script lmao, if you struggle understanding this then gl
# You can always ask me if you need help understanding a piece of code.

import packer
import random
import math
import plistlib
import ast
import string
from PIL import Image, ImageFile
import io
import base64
import zlib
import gzip
import csv
import pefile

ImageFile.LOAD_TRUNCATED_IMAGES = True

# Generated by Gemini (modified by me and claude)
def parse_bmfont_text(file_data):
    font_data = {"info": {}, "common": {}, "page": {}, "chars": [], "kernings": []}
    for line in file_data:
        parts = line.strip().split()
        if not parts:
            continue
        tag = parts[0]
        attrs = {}
        for item in parts[1:]:
            if "=" in item:
                key, val = item.split("=", 1)
                val = val.strip('"')
                if val.lstrip("-").isdigit():
                    val = int(val)
                attrs[key] = val
        if tag in ["info", "common", "page"]:
            font_data[tag] = attrs
        elif tag == "char":
            font_data["chars"].append(attrs)
        elif tag == "kerning":
            font_data["kernings"].append(attrs)
    return font_data

# Generated by Claude
def serialize_bmfont_text(font_data):
    lines = []

    def format_attrs(attrs):
        parts = []
        for key, val in attrs.items():
            if isinstance(val, str) and (" " in val or not val.lstrip("-").lstrip("0123456789").isdigit()):
                parts.append(f'{key}="{val}"')
            else:
                parts.append(f"{key}={val}")
        return " ".join(parts)

    if font_data.get("info"):
        lines.append(f"info {format_attrs(font_data['info'])}")
    if font_data.get("common"):
        lines.append(f"common {format_attrs(font_data['common'])}")
    if font_data.get("page"):
        lines.append(f"page {format_attrs(font_data['page'])}")
    if font_data.get("chars"):
        lines.append(f"chars count={len(font_data['chars'])}")
        for char in font_data["chars"]:
            lines.append(f"char {format_attrs(char)}")
    if font_data.get("kernings"):
        lines.append(f"kernings count={len(font_data['kernings'])}")
        for kerning in font_data["kernings"]:
            lines.append(f"kerning {format_attrs(kerning)}")
    return "\n".join(lines)

# Generated by Claude
def get_all_paths(d, current_path=None):
    if current_path is None:
        current_path = []

    paths = []

    for key, value in d.items():
        path = current_path + [key]

        if isinstance(value, dict):
            paths.extend(get_all_paths(value, path))
        else:
            paths.append(path)

    return paths


# Generated by Claude
def set_nested_value(d, path, new_value):
    for key in path[:-1]:
        d = d[key]

    d[path[-1]] = new_value


def corrupt_gddir(file, corruption_level) -> bytes:
    print("Corrupting .gddir file...")

    files = packer.read_gd_dir(file, packer.read_allowed_files("allowed-files.dat"))

    corrupted_bytes = 0
    loaded_images = {}
    loaded_plists = {}

    with open(file, "rb") as af:
        data = af.read()
        data_size = len(data) - int.from_bytes(data[0:4], byteorder="little")
        total_corrupted_bytes = math.floor(data_size * corruption_level)

    file_names = list(files.keys())

    while corrupted_bytes < total_corrupted_bytes:
        random_file_name = random.choice(file_names)

        if random_file_name.endswith(".ogg") or random_file_name.endswith(".mp3"):
            random_file = bytearray(files[random_file_name])

            for i in range(20):
                random_file[random.randint(0, len(random_file) - 1)] = random.randint(0, 255)
            
            files[random_file_name] = bytes(random_file)
            corrupted_bytes += 20
        elif random_file_name.endswith(".plist"):
            if random.randint(0, 1) == 1:
                continue
            if random_file_name not in loaded_plists:
                random_file = bytearray(files[random_file_name]).lstrip(b"\r\n")
                loaded_plists[random_file_name] = plistlib.loads(random_file, fmt=plistlib.FMT_XML)

            loaded = loaded_plists[random_file_name]
            p = get_all_paths(loaded)
            random_path = random.choice(p)

            current_value = loaded

            for key in random_path:
                current_value = current_value[key]

            random_element = 0
            image_size = [0, 0]

            if "metadata" in loaded:
                image_size = loaded["metadata"]["size"]

                image_size = image_size.replace("{", "[")
                image_size = image_size.replace("}", "]")
                image_size = ast.literal_eval(image_size)
            if type(current_value) is bool:
                random_element = not current_value

                if random_path[len(random_path) - 1] == "textureRotated":
                    # Reverse textureRect
                    text_size = loaded["frames"][random_path[len(random_path) - 2]]["textureRect"]

                    text_size = text_size.replace("{", "[").replace("}", "]")
                    text_size = ast.literal_eval(text_size)

                    temp = text_size[1][1]
                    text_size[1][1] = text_size[1][0]
                    text_size[1][0] = temp

                    text_size = str(text_size).replace("[", "{").replace("]", "}").replace(" ", "")

                    loaded["frames"][random_path[len(random_path) - 2]]["textureRect"] = text_size
                    
                    # Reverse spriteSize
                    sprite_size = loaded["frames"][random_path[len(random_path) - 2]]["spriteSize"]

                    sprite_size = sprite_size.replace("{", "[").replace("}", "]")
                    sprite_size = ast.literal_eval(sprite_size)

                    temp = sprite_size[1]
                    sprite_size[1] = sprite_size[0]
                    sprite_size[0] = temp

                    sprite_size = str(sprite_size).replace("[", "{").replace("]", "}").replace(" ", "")

                    loaded["frames"][random_path[len(random_path) - 2]]["spriteSize"] = sprite_size

                    # Reverse spriteSourceSize
                    sprite_source_size = loaded["frames"][random_path[len(random_path) - 2]]["spriteSourceSize"]

                    sprite_source_size = sprite_source_size.replace("{", "[").replace("}", "]")
                    sprite_source_size = ast.literal_eval(sprite_source_size)

                    temp = sprite_source_size[1]
                    sprite_source_size[1] = sprite_source_size[0]
                    sprite_source_size[0] = temp

                    sprite_source_size = str(sprite_source_size).replace("[", "{").replace("]", "}").replace(" ", "")

                    loaded["frames"][random_path[len(random_path) - 2]]["spriteSourceSize"] = sprite_source_size
            elif type(current_value) is str:
                if current_value.startswith("{"):
                    current_value = current_value.replace("{", "[").replace("}", "]")
                    literal_list = ast.literal_eval(current_value)

                    random_element = random.randint(0, len(literal_list) - 1)

                    if type(literal_list[random_element]) is list:
                        random_element_2 = random.randint(0, len(literal_list[random_element]) - 1)

                        if random_path[-1] == "textureRect":
                            literal_list[random_element][random_element_2] += random.randint(-100, 100)

                            if random_element == 0:
                                if literal_list[0][random_element_2] < 0:
                                    literal_list[0][random_element_2] = 0
                                
                                if loaded["frames"][random_path[-2]]["textureRotated"]:
                                    if literal_list[0][random_element_2] + literal_list[1][abs(random_element_2 - 1)] > image_size[random_element_2]:
                                        literal_list[0][random_element_2] = image_size[random_element_2] - literal_list[1][abs(random_element_2 - 1)]
                                else:
                                    if literal_list[0][random_element_2] + literal_list[1][random_element_2] > image_size[random_element_2]:
                                        literal_list[0][random_element_2] = image_size[random_element_2] - literal_list[1][random_element_2]
                            else:
                                if loaded["frames"][random_path[-2]]["textureRotated"]:
                                    if literal_list[1][abs(random_element_2 - 1)] < 0:
                                        literal_list[1][abs(random_element_2 - 1)] = 0
                                    
                                    if literal_list[1][abs(random_element_2 - 1)] + literal_list[0][random_element_2] > image_size[random_element_2]:
                                        literal_list[1][abs(random_element_2 - 1)] = image_size[random_element_2] - literal_list[0][random_element_2]
                                else:
                                    if literal_list[1][random_element_2] < 0:
                                        literal_list[1][random_element_2] = 0
                                    
                                    if literal_list[1][random_element_2] + literal_list[0][random_element_2] > image_size[random_element_2]:
                                        literal_list[1][random_element_2] = image_size[random_element_2] - literal_list[0][random_element_2]

                        corrupted_bytes += len(str(literal_list[random_element][random_element_2]))
                    else:
                        if random_path[-1] == "spriteSize":
                            random_value = random.randint(-100, 100)
                            literal_list[random_element] += random_value

                            if literal_list[random_element] < 1:
                                literal_list[random_element] = 1
                            
                            texture_rect_list = loaded["frames"][random_path[len(random_path) - 2]]["textureRect"]

                            texture_rect_list = texture_rect_list.replace("{", "[")
                            texture_rect_list = texture_rect_list.replace("}", "]")

                            texture_rect_list = ast.literal_eval(texture_rect_list)

                            if loaded["frames"][random_path[-2]]["textureRotated"]:
                                if literal_list[abs(random_element - 1)] + texture_rect_list[0][random_element] > image_size[random_element]:
                                    literal_list[abs(random_element - 1)] = image_size[random_element] - texture_rect_list[0][random_element]
                            else:
                                if literal_list[random_element] + texture_rect_list[0][random_element] > image_size[random_element]:
                                    literal_list[random_element] = image_size[random_element] - texture_rect_list[0][random_element]
                            
                            texture_rect_list[1] = literal_list
                            
                            texture_rect_list = str(texture_rect_list)
                            texture_rect_list = texture_rect_list.replace("[", "{")
                            texture_rect_list = texture_rect_list.replace("]", "}")
                            texture_rect_list = texture_rect_list.replace(" ", "")

                            literal_list_converted = str(literal_list)
                            literal_list_converted = literal_list_converted.replace("[", "{").replace("]", "}").replace(" ", "")

                            loaded["frames"][random_path[len(random_path) - 2]]["textureRect"] = texture_rect_list
                            loaded["frames"][random_path[len(random_path) - 2]]["spriteSourceSize"] = literal_list_converted
                        elif random_path[-1] == "spriteSourceSize":
                            random_value = random.randint(-100, 100)
                            literal_list[random_element] += random_value

                            if literal_list[random_element] < 1:
                                literal_list[random_element] = 1
                            
                            texture_rect_list = loaded["frames"][random_path[len(random_path) - 2]]["textureRect"]

                            texture_rect_list = texture_rect_list.replace("{", "[")
                            texture_rect_list = texture_rect_list.replace("}", "]")

                            texture_rect_list = ast.literal_eval(texture_rect_list)

                            if loaded["frames"][random_path[-2]]["textureRotated"]:
                                if literal_list[abs(random_element - 1)] + texture_rect_list[0][random_element] > image_size[random_element]:
                                    literal_list[abs(random_element - 1)] = image_size[random_element] - texture_rect_list[0][random_element]
                            else:
                                if literal_list[random_element] + texture_rect_list[0][random_element] > image_size[random_element]:
                                    literal_list[random_element] = image_size[random_element] - texture_rect_list[0][random_element]
                            
                            texture_rect_list[1] = literal_list
                            
                            texture_rect_list = str(texture_rect_list)
                            texture_rect_list = texture_rect_list.replace("[", "{")
                            texture_rect_list = texture_rect_list.replace("]", "}")
                            texture_rect_list = texture_rect_list.replace(" ", "")

                            literal_list_converted = str(literal_list)
                            literal_list_converted = literal_list_converted.replace("[", "{").replace("]", "}").replace(" ", "")

                            loaded["frames"][random_path[len(random_path) - 2]]["textureRect"] = texture_rect_list
                            loaded["frames"][random_path[len(random_path) - 2]]["spriteSize"] = literal_list_converted
                        elif random_path[-1] != "size":
                            random_value = random.randint(-100, 100)
                            literal_list[random_element] += random_value

                        corrupted_bytes += len(str(literal_list[random_element]))
                    
                    random_element = str(literal_list)
                    random_element = random_element.replace("[", "{")
                    random_element = random_element.replace("]", "}")
                    random_element = random_element.replace(" ", "")
                if random_element == 0:
                    random_element = current_value
            elif type(current_value) is list:
                if current_value:
                    random_choice = random.randint(0, len(current_value) - 1)

                    # if type(current_value[random_choice]) is int:
                    #     current_value[random_choice] += random.randint(-5, 5)
                    #     corrupted_bytes += len(str(current_value[random_choice]))
                    if type(current_value[random_choice]) is str:
                        random_index = random.randint(0, len(current_value[random_choice]) - 1)

                        current_value[random_choice][random_index] = random.choice(string.ascii_letters)
                        corrupted_bytes += 1
                    if type(current_value[random_choice]) is bool:
                        current_value[random_choice] = not current_value[random_choice]

                        corrupted_bytes += len(str(current_value[random_choice]))

                random_element = current_value
            # elif type(current_value) is int:
            #     random_element = current_value + random.randint(-100, 100)
            #     corrupted_bytes += len(str(random_element))
            # elif type(current_value) is float:
            #     random_element = current_value + random.uniform(-100.0, 100.0)
            #     corrupted_bytes += len(str(random_element))
            else:
                pass
                #print("Unhandled type when corrupting .plist file: " + str(type(current_value)))

            set_nested_value(loaded, random_path, random_element)

            # for some dumb reason, the format key under the metadata of the plist file would be set to 0
            # as far as i know nothing in my code changes it, and it never increases, it always just becomes 0
            # instead of trying to find the cause, i've instead opted to just change it at the end so that it stays 3 and actually displays in gd
            if "metadata" in loaded:
                loaded["metadata"]["format"] = 3
        elif random_file_name.endswith(".png"):
            # Refactored by Claude
            if random_file_name not in loaded_images:
                image = Image.open(io.BytesIO(files[random_file_name]), formats=["PNG"]).convert("RGBA")
                loaded_images[random_file_name] = (image, image.load())

            image, pixels = loaded_images[random_file_name]

            for i in range(25):
                pixels[random.randint(0, image.width - 1), random.randint(0, image.height - 1)] = (
                    random.randint(0, 255), random.randint(0, 255),
                    random.randint(0, 255), random.randint(0, 255)
                )
            corrupted_bytes += 100
        elif random_file_name.endswith(".fnt"):
            data = parse_bmfont_text(files[random_file_name].decode().split("\n"))
            
            for i in range(10):
                if random.randint(0, 1) == 0:
                    random_element = random.randint(0, len(data["chars"]) - 1)
                    random_key = random.choice(list(data["chars"][random_element].keys()))

                    image_size_x = data["common"]["scaleW"]
                    image_size_y = data["common"]["scaleH"]

                    if type(data["chars"][random_element][random_key]) is int:
                        if random_key != "id" and random_key != "page" and random_key != "chnl":
                            data["chars"][random_element][random_key] += random.randint(-50, 50)

                            if data["chars"][random_element][random_key] < 1:
                                data["chars"][random_element][random_key] = 1

                            if random_key == "x":
                                if data["chars"][random_element]["x"] + data["chars"][random_element]["width"] > image_size_x:
                                    data["chars"][random_element]["x"] = image_size_x - data["chars"][random_element]["width"]
                            elif random_key == "y":
                                if data["chars"][random_element]["y"] + data["chars"][random_element]["height"] > image_size_y:
                                    data["chars"][random_element]["y"] = image_size_y - data["chars"][random_element]["height"]
                            elif random_key == "width":
                                if data["chars"][random_element]["x"] + data["chars"][random_element]["width"] > image_size_x:
                                    data["chars"][random_element]["width"] = image_size_x - data["chars"][random_element]["x"]
                            elif random_key == "height":
                                if data["chars"][random_element]["y"] + data["chars"][random_element]["height"] > image_size_y:
                                    data["chars"][random_element]["height"] = image_size_y - data["chars"][random_element]["y"]
                            
                            corrupted_bytes += len(str(data["chars"][random_element][random_key]))
                    if random_key == "letter":
                        other_random_element = random.randint(0, len(data["chars"]) - 1)

                        temp = data["chars"][other_random_element]["letter"]
                        data["chars"][other_random_element]["letter"] = data["chars"][random_element]["letter"]
                        data["chars"][random_element]["letter"] = temp
                else:
                    if len(data["kernings"]) > 1:
                        random_element = random.randint(0, len(data["kernings"]) - 1)
                        random_key = random.choice(list(data["kernings"][random_element].keys()))

                        if type(data["kernings"][random_element][random_key]) is int:
                            data["kernings"][random_element][random_key] += random.randint(-50, 50)
                            
                            corrupted_bytes += len(str(data["kernings"][random_element][random_key]))

            files[random_file_name] = serialize_bmfont_text(data).encode()

        elif random_file_name.endswith(".txt"):
            base64_decoded = base64.urlsafe_b64decode(files[random_file_name])
            decompressed = zlib.decompress(base64_decoded, 15 | 32)
            level_string = decompressed.decode()

            components = level_string.split(";")
            components.pop(0)

            if len(components) == 0:
                continue

            random_index = random.randint(0, len(components) - 1)
            components[random_index] = components[random_index].split(",")

            if len(components[random_index]) > 1:
                components[random_index][1] = str(random.randint(1, 4539))
                components[random_index][3] = str(random.randint(1, 10000))
                components[random_index][5] = str(random.randint(1, 400))

                conjoined = ",".join(components[random_index])
                components[random_index] = conjoined

                level_string = ";".join(components)

                gzipped = gzip.compress(level_string.encode())
                base64_encoded = base64.urlsafe_b64encode(gzipped).decode()

                files[random_file_name] = base64_encoded.encode()

                corrupted_bytes += 10


    print("Saving .plist files...")

    for name, data in loaded_plists.items():
        files[name] = plistlib.dumps(data, fmt=plistlib.FMT_XML)
        #print(name)

    print("Saving .png files...")

    for name, (image, _) in loaded_images.items():
        buf = io.BytesIO()
        image.save(buf, format="PNG")
        files[name] = buf.getvalue()

        #print(name)
    
    print("Patching level integrity check...")
    
    # GD has a level integrity system that checks the size of the level to ensure it has not been tampered with.
    # This code patches the function so that it always returns true, no matter what.

    bytearraya = bytearray(files["gd-directory/GeometryDash.exe"])
    bytearraya[3327936:3327942] = bytearray(b"\xb8\x01\x00\x00\x00\xc3")

    # b8 01 00 00 00   MOV EAX, 0x1
    # c3               RET
    
    files["gd-directory/GeometryDash.exe"] = bytes(bytearraya)

    print("Successfully corrupted .gddir file!")

    return packer.dict_to_gd_dir(files)



